OBJDIR = .\Obj
LIBDIR = ..\lib
INCDIR = ..\src
BINDIR = .

all: $(BINDIR)/example

$(BINDIR)\example: example.cxx $(INCDIR)\sl.h $(INCDIR)\sm.h $(LIBDIR)\libsl.lib $(LIBDIR)\libsm.lib
        @$(CC) -o $@ -I$(INCDIR) example.cxx $(LIBDIR)\libsl.lib $(LIBDIR)\libsm.lib /link winmm.lib

